"""empty message

Revision ID: d27f3618771a
Revises: 
Create Date: 2018-08-08 08:12:31.436824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27f3618771a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gejala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=93), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_identitas', sa.String(length=100), nullable=True),
    sa.Column('nama', sa.String(length=50), nullable=True),
    sa.Column('alamat', sa.String(length=100), nullable=True),
    sa.Column('tgl_lahir', sa.Date(), nullable=True),
    sa.Column('jenis_kelamin', sa.CHAR(length=1), nullable=True),
    sa.Column('history', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penyakit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('deskripsi', sa.String(length=255), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('publish', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_model')
    op.drop_table('penyakit')
    op.drop_table('patients')
    op.drop_table('login')
    op.drop_table('gejala')
    # ### end Alembic commands ###
